version: "3.8"

services:
  frontend:
    container_name: frontend
    image: fst-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: yarn start
    ports:
      - 3000:3000

  backend:
    container_name: backend
    image: fst-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: yarn start:dev
    ports:
      - 8000:8000
